In [27]:
import numpy as np
import os
os.chdir('..')
import logging
import yaml
from helpers import Config
from telemanom.channel import Channel
from telemanom.detector import Detector
from sklearn.preprocessing import MinMaxScaler

In [11]:
df = np.load('data//train//A-1.npy')

In [40]:
df

array([[0.999, 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.999, 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.999, 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       ...,
       [0.999, 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.999, 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.999, 0.   , 0.   , ..., 0.   , 0.   , 0.   ]])

In [28]:
scaler = MinMaxScaler()
df_trans = scaler.fit_transform(df)

In [39]:
data[174, :62, 6]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
arr = df_trans
l_s = 250
n_predictions = 10
data = []
for i in range(len(arr) - l_s - n_predictions):
    data.append(arr[i:i + l_s + n_predictions])
data = np.array(data)

In [25]:
print(data.shape)
print(data[:, :-n_predictions, :].shape)
print(data[:, -n_predictions:, 0].shape)

(2620, 260, 25)
(2620, 250, 25)
(2620, 10)


In [22]:
cfg_path = "config.yaml"
config = Config(cfg_path)

ch = Channel(config,"A-1")

In [23]:
ch.id

'A-1'

In [67]:
print(ch.y_train)

[[0.999 0.999 0.999 ... 0.999 0.999 0.999]
 [0.999 0.999 0.999 ... 0.999 0.999 0.999]
 [0.999 0.999 0.999 ... 0.999 0.999 0.999]
 ...
 [0.999 0.999 0.999 ... 0.999 0.999 0.999]
 [0.999 0.999 0.999 ... 0.999 0.999 0.999]
 [0.999 0.999 0.999 ... 0.999 0.999 0.999]]


In [6]:
det = Detector()

82 channels found for processing.


In [7]:
det.run()

Stream # 1: A-1
normalized prediction error: 0.01
[(2030, 2074)]
[0]
1 anomalies found
anomaly sequences start/end indices: [(4730, 4869)]
number of test values: 8380
anomaly scores: [{'start_idx': 4480, 'end_idx': 4549, 'score': 3.2014438937526872}, {'start_idx': 4550, 'end_idx': 4619, 'score': 2.6588575318785037}]

Stream # 2: A-2
normalized prediction error: 0.07
[(2030, 2092)]
[0]
3 anomalies found
anomaly sequences start/end indices: [(1043, 1345), (1463, 1716), (4450, 4659)]
number of test values: 7654
anomaly scores: [{'start_idx': 793, 'end_idx': 1095, 'score': 1.8545669243939444}, {'start_idx': 1213, 'end_idx': 1466, 'score': 1.901390805835339}, {'start_idx': 4200, 'end_idx': 4269, 'score': 2.377316696619421}, {'start_idx': 4270, 'end_idx': 4339, 'score': 3.832082350265727}, {'start_idx': 4340, 'end_idx': 4409, 'score': 3.8800572288975474}]

Stream # 3: A-3
normalized prediction error: 0.05
[(974, 1211), (1828, 2028)]
[1, 0]
[(2030, 2060)]
[0]
[(2030, 2099)]
[0]
[(2030, 2099)]

anomaly scores: [{'start_idx': 4830, 'end_idx': 4899, 'score': 8.179095469698204}, {'start_idx': 4900, 'end_idx': 4969, 'score': 10.028533066136328}, {'start_idx': 4970, 'end_idx': 5039, 'score': 8.663958069178404}, {'start_idx': 5040, 'end_idx': 5093, 'score': 7.194747687434269}]

Stream # 17: D-14
normalized prediction error: 0.03
1 anomalies found
anomaly sequences start/end indices: [(1891, 2119)]
number of test values: 2365
anomaly scores: [{'start_idx': 1641, 'end_idx': 1869, 'score': 10.025303505940375}]

Stream # 18: D-15
normalized prediction error: 0.15
1 anomalies found
anomaly sequences start/end indices: [(1751, 2147)]
number of test values: 1898
anomaly scores: [{'start_idx': 1501, 'end_idx': 1897, 'score': 3.3455765655852594}]

Stream # 19: D-16
normalized prediction error: 0.17
1 anomalies found
anomaly sequences start/end indices: [(726, 957)]
number of test values: 1931
anomaly scores: [{'start_idx': 476, 'end_idx': 707, 'score': 5.48277629855431}]

Stream # 20: D-2
n

C:\Users\wassinkj\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\wassinkj\Anaconda3\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\Users\wassinkj\Anaconda3\lib\site-packages\numpy\core\_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\wassinkj\Anaconda3\lib\site-packages\numpy\core\_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
C:\Users\wassinkj\Anaconda3\lib\site-packages\numpy\core\_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


[(2030, 2063)]
[0]
2 anomalies found
anomaly sequences start/end indices: [(6410, 6619), (7326, 7395)]
number of test values: 7146
anomaly scores: [{'start_idx': 6160, 'end_idx': 6229, 'score': 9.883358214478907}, {'start_idx': 6230, 'end_idx': 6299, 'score': 10.64324279249464}, {'start_idx': 6300, 'end_idx': 6369, 'score': 8.10845666922361}, {'start_idx': 7076, 'end_idx': 7145, 'score': 7.83465413030666}]

Stream # 28: E-1
normalized prediction error: 0.07
[(2030, 2072)]
[0]
3 anomalies found
anomaly sequences start/end indices: [(1751, 2001), (5010, 5149), (5570, 5965)]
number of test values: 8256
anomaly scores: [{'start_idx': 1501, 'end_idx': 1751, 'score': 3.370114482430331}, {'start_idx': 4760, 'end_idx': 4829, 'score': 8.02425671004024}, {'start_idx': 4830, 'end_idx': 4899, 'score': 6.015687399374383}, {'start_idx': 5320, 'end_idx': 5389, 'score': 7.506587332861675}, {'start_idx': 5390, 'end_idx': 5459, 'score': 9.328760311602148}, {'start_idx': 5460, 'end_idx': 5529, 'score': 9

Stream # 40: E-9
normalized prediction error: 0.05
[(500, 695)]
[0]
[(2030, 2099)]
[0]
[(2030, 2099)]
[0]
[(2030, 2055)]
[0]
[(2030, 2072)]
[0]
[(2030, 2099)]
[0]
[(2030, 2066)]
[0]
[(2030, 2099)]
[0]
[(2030, 2099)]
[0]
[(2030, 2049)]
[0]
[(2030, 2099)]
[0]
[(2092, 2161)]
[0]
1 anomalies found
anomaly sequences start/end indices: [(5710, 5919)]
number of test values: 8042
anomaly scores: [{'start_idx': 5460, 'end_idx': 5529, 'score': 0.9955577576882938}, {'start_idx': 5530, 'end_idx': 5599, 'score': 1.000330877033821}, {'start_idx': 5600, 'end_idx': 5669, 'score': 1.060322064489463}]

Stream # 41: F-1
normalized prediction error: 0.10
[(2030, 2099)]
[0]
[(2030, 2099)]
[0]
[(2030, 2050)]
[0]
[(2030, 2099)]
[0]
[(2030, 2096)]
[0]
[(2030, 2099)]
[0]
[(2030, 2090)]
[0]
[(2030, 2099)]
[0]
[(2030, 2099)]
[0]
[(2030, 2097)]
[0]
[(2030, 2099)]
[0]
[(2030, 2090)]
[0]
[(2030, 2099)]
[0]
[(2030, 2099)]
[0]
1 anomalies found
anomaly sequences start/end indices: [(7530, 7599)]
number of test values

number of test values: 8245
anomaly scores: [{'start_idx': 1880, 'end_idx': 2099, 'score': 2.0284713472409055}, {'start_idx': 2940, 'end_idx': 3009, 'score': 2.1372898817915145}, {'start_idx': 3010, 'end_idx': 3079, 'score': 2.163556613516779}, {'start_idx': 3290, 'end_idx': 3359, 'score': 2.1331476542631735}, {'start_idx': 3360, 'end_idx': 3429, 'score': 2.2936228235904377}, {'start_idx': 4270, 'end_idx': 4339, 'score': 0.9175092986586291}]

Stream # 62: P-10
normalized prediction error: 0.06
1 anomalies found
anomaly sequences start/end indices: [(4590, 5009)]
number of test values: 5840
anomaly scores: [{'start_idx': 4340, 'end_idx': 4409, 'score': 9.583220915591768}, {'start_idx': 4410, 'end_idx': 4479, 'score': 11.508316476492856}, {'start_idx': 4480, 'end_idx': 4549, 'score': 10.41027669523142}, {'start_idx': 4550, 'end_idx': 4619, 'score': 9.844461137308446}, {'start_idx': 4620, 'end_idx': 4689, 'score': 9.343835247249608}, {'start_idx': 4690, 'end_idx': 4759, 'score': 8.9486025

Stream # 79: T-4
normalized prediction error: 0.10
[(250, 464)]
[0]
[(686, 894)]
[0]
0 anomalies found
anomaly sequences start/end indices: []
number of test values: 1957
anomaly scores: []

Stream # 80: T-5
normalized prediction error: 0.01
1 anomalies found
anomaly sequences start/end indices: [(1114, 1381)]
number of test values: 1958
anomaly scores: [{'start_idx': 864, 'end_idx': 1131, 'score': 12.319131674587176}]

Stream # 81: T-8
normalized prediction error: 0.04
2 anomalies found
anomaly sequences start/end indices: [(786, 1036), (1273, 1488)]
number of test values: 1259
anomaly scores: [{'start_idx': 536, 'end_idx': 786, 'score': 4.407013980375386}, {'start_idx': 1023, 'end_idx': 1238, 'score': 4.2558926114087425}]

Stream # 82: T-9
normalized prediction error: 0.16
0 anomalies found
anomaly sequences start/end indices: []
number of test values: 836
anomaly scores: []

Final Totals:
-----------------
Total channel sets evaluated: 82
Total anomalies found: 112
Avg normalized pr